// SPDX-License-Identifier: AGPL-3.0-only
//
// Cyberdriver branding overlay — runtime initialization of APP_NAME and
// BUILTIN_SETTINGS. Gated by the `cyberdesk` Cargo feature; included
// from src/lib.rs.
//
// This module exists to keep our diff against upstream RustDesk small.
// Rather than patching the upstream `libs/hbb_common/src/config.rs`
// submodule (which would create rebase conflicts), we exploit the fact
// that `APP_NAME` and `BUILTIN_SETTINGS` are runtime `RwLock`s already
// designed for the RustDesk Pro custom-client mechanism.
//
// Constants below are the source of truth for the branded build. They
// mirror `branding/app_strings.json` and `branding/hbbs_pubkey.txt`.

use hbb_common::config::{APP_NAME, BUILTIN_SETTINGS};

// ---- Branding constants (mirror branding/app_strings.json) ----

pub const APP_NAME_STR: &str = "Cyberdriver";
pub const APP_COMPANY: &str = "Cyberdesk Inc.";
pub const SUPPORT_URL: &str = "https://cyberdesk.io/support";
pub const AGPL_SOURCE_URL_CLIENT: &str = "https://github.com/cyberdesk-hq/cyberdriver-new";
pub const AGPL_SOURCE_URL_SERVER: &str = "https://github.com/cyberdesk-hq/cyberdriver-server";
pub const URL_SCHEME: &str = "cyberdesk";

// Network defaults — overridable at runtime via Settings UI (M7).
//
// The `cyberdesk-dev` Cargo feature flips these to the -dev hosts so
// dev builds talk to the dev Fly hbbs/hbbr + dev Cyberdesk cloud.
// See branding/README.md and the M2 plan for the dev/prod story.
//
// To produce a prod build:  cargo build --features cyberdesk
// To produce a dev build:   cargo build --features cyberdesk-dev

#[cfg(not(feature = "cyberdesk-dev"))]
pub const RENDEZVOUS_SERVER: &str = "hbbs.cyberdesk.io";
#[cfg(feature = "cyberdesk-dev")]
pub const RENDEZVOUS_SERVER: &str = "hbbs-dev.cyberdesk.io";

#[cfg(not(feature = "cyberdesk-dev"))]
pub const RELAY_SERVER: &str = "hbbr.cyberdesk.io";
#[cfg(feature = "cyberdesk-dev")]
pub const RELAY_SERVER: &str = "hbbr-dev.cyberdesk.io";

#[cfg(not(feature = "cyberdesk-dev"))]
pub const API_SERVER: &str = "https://api.cyberdesk.io";
#[cfg(feature = "cyberdesk-dev")]
pub const API_SERVER: &str = "https://cyberdesk-api-dev.fly.dev";

#[cfg(not(feature = "cyberdesk-dev"))]
pub const UPDATE_FEED_URL: &str = "https://updates.cyberdesk.io/manifest.json";
#[cfg(feature = "cyberdesk-dev")]
pub const UPDATE_FEED_URL: &str = "https://updates-dev.cyberdesk.io/manifest.json";

/// Returns "prod" or "dev" based on which feature is active. Useful for
/// log lines and the About dialog so users can tell at a glance which
/// build they have.
pub const fn build_env() -> &'static str {
    #[cfg(feature = "cyberdesk-dev")]
    {
        "dev"
    }
    #[cfg(not(feature = "cyberdesk-dev"))]
    {
        "prod"
    }
}

// HBBS Ed25519 public key (base64). Each environment has its own
// keypair (generated by `cyberdriver-server/scripts/setup-hbbs-keypair.sh`
// during M2) so dev clients don't trust the prod hbbs and vice versa.
// Filled in by hand once the secrets are set on Fly.
//
// Empty string = let hbb_common fall back to the built-in upstream
// key. Useful for local development against a self-built hbbs but NOT
// secure for production.

#[cfg(not(feature = "cyberdesk-dev"))]
pub const HBBS_PUBKEY: &str = "zhJ/30tgM6fCP+cJro8DjPN2WnswhMiowPkehilsMYc=";
#[cfg(feature = "cyberdesk-dev")]
pub const HBBS_PUBKEY: &str = "EHHHwBfzjJasItIOwAJAI60Jj64uJu4rpI1cdE4ulhI=";

/// Initialize Cyberdriver branding. Must be called early in the
/// process startup, before any code reads APP_NAME or BUILTIN_SETTINGS.
///
/// Idempotent — calling twice has the same effect as calling once.
pub fn init() {
    if let Ok(mut name) = APP_NAME.write() {
        *name = APP_NAME_STR.to_owned();
    }

    if let Ok(mut builtin) = BUILTIN_SETTINGS.write() {
        if !RENDEZVOUS_SERVER.is_empty() {
            builtin.insert(
                "custom-rendezvous-server".to_owned(),
                RENDEZVOUS_SERVER.to_owned(),
            );
        }
        if !RELAY_SERVER.is_empty() {
            builtin.insert("relay-server".to_owned(), RELAY_SERVER.to_owned());
        }
        if !API_SERVER.is_empty() {
            builtin.insert("api-server".to_owned(), API_SERVER.to_owned());
        }
        if !HBBS_PUBKEY.is_empty() {
            builtin.insert("key".to_owned(), HBBS_PUBKEY.to_owned());
        }
    }
}

/// AGPL §13 source-link string suitable for the `Server:` HTTP header
/// and the `--source` CLI flag output. Used by both the cyberdesk_tunnel
/// module (M4) and the Cyberdriver local HTTP listener.
pub fn server_header_source_link() -> String {
    format!("Cyberdriver (AGPL source: {AGPL_SOURCE_URL_CLIENT})")
}
