name: Cyberdriver Test Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "GitHub release tag to create/update"
        required: false
        default: "test"

jobs:
  build-windows-msi:
    uses: ./.github/workflows/release-windows-msi.yml
    secrets: inherit
    with:
      release_tag: ${{ inputs.release_tag }}