name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "GitHub release tag to create/update"
        required: false
        default: "test"
      macos_only:
        description: "Build only macOS desktop DMGs"
        required: false
        type: boolean
        default: false
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  run-flutter-tag-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.release_tag || github.ref_name }}
      macos_only: ${{ github.event_name == 'workflow_dispatch' && inputs.macos_only }}